#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED



#define WIDTH 600
#define HEIGHT 600
#define NBR_DE_CASES_HORIZONTALES 20
#define NBR_DE_CASES_VERTICALES 20
#define CHEMIN_D_ACCES_FICHIER_NIVEAU "assets/maps/map1.dat"
#define VITESSE_DES_JOUEURS 10
#define CHEMIN_POLICE_ECRITURE_MONTSERRAT "assets/fonts/Montserrat-Regular.ttf"
#define CHEMIN_POLICE_ECRITURE_MONTSERRAT_BOLD "assets/fonts/Montserrat-Bold.ttf"

#endif // CONSTANTES_H_INCLUDED
