#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED



#define WIDTH 600
#define HEIGHT 600
#define NBR_DE_CASES_HORIZONTALES 20
#define NBR_DE_CASES_VERTICALES 20

#define TAILLE_MAX_NOM_COMPTE 20
#define NBR_MAX_COMPTES 50


#define VITESSE_DES_JOUEURS 10

#define LONGUEUR_EXPLOSION_BOMBE 3
#define NB_CASES_AFFECTEES_EXPLOSIONS_BOMBES (LONGUEUR_EXPLOSION_BOMBE * 4 + 1) * 4

#define LONGUEUR_MAX_NOM_JOUEUR 8

#define CHEMIN_D_ACCES_FICHIER_NIVEAU "assets/maps/map1.dat"
#define CHEMIN_D_ACCES_FICHIER_COMPTES_JOUEURS "assets/datas/comptes_joueurs.dat"
#define CHEMIN_POLICE_ECRITURE_MONTSERRAT "assets/fonts/montserrat_regular.ttf"
#define CHEMIN_POLICE_ECRITURE_MONTSERRAT_BOLD "assets/fonts/montserrat_bold.ttf"
#define CHEMIN_POLICE_ECRITURE_VERDANA "assets/fonts/verdana.ttf"

#endif // CONSTANTES_H_INCLUDED
